[DATASET]
path = data/trajFujianV2
device = cuda
; mean = 0
; std = 6511.2666
mean = 19.5491
std = 141.7185


[TRAIN]
model_name = TrajLSTM
model_config_path = config/%(model_name)s.ini
save_path = weights/%(model_name)s/30_history_step
lr = 0.0001
max_epoch = 70
batch_size = 64

[EVALUATE]
epoch = 5
batch_size = 64

[TEST]
batch_size = 64

[INFERENCE]

[LOG]
save_path = new1