[DATASET]
path = data/trajFujianV2
device = cuda
; mean = 0
; std = 6511.2666
mean = 19.5491
std = 141.7185
; mean = 0.1620739108680599
; std = 0.27422189414298254
; l = 0.0111460429649723213
; l = 0.0055730214824861605
; l = 0.0027865107412430802

[TRAIN]
; model_name = TrajLSTM
model_name = TrajPredTransformerV1
model_config_path = config/%(model_name)s.ini
save_path = weights/%(model_name)s/new_norm_exp_none_mean_std
lr = 0.0001
max_epoch = 100
batch_size = 64

[EVALUATE]
epoch = 5
batch_size = 64

[TEST]
batch_size = 64

[INFERENCE]

[LOG]
save_path = new1